#!/bin/bash
isExistApp = `pgrep apache2`
if [[ -n  $isExistApp ]]; then
    service apache2 stop        
fi


#isExistApp = `pgrep httpd`
#if [[ -n  $isExistApp ]]; then
    #service httpd stop        
#fi

